arb-dir: lib/l10n
output-class: ReviLocalizations
output-localization-file: localizations.dart
output-dir: lib/l10n/generated
template-arb-file: intl_en.arb
preferred-supported-locales: ["en"]
synthetic-package: false
nullable-getter: false
format: false
untranslated-messages-file: lib/l10n/untranslated.json